- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config', '~/.local']

- create:
    - ~/tmp
    # terminal history folder
    - ~/.cache/terminal
    # vim files
    - ~/.cache/vim/swap
    - ~/.cache/vim/undo
    - ~/.cache/vim

- link:
    # home stuff
    ~/.profile: home/.profile
    ~/.bashrc: home/.bashrc
    ~/.bash_profile: home/.bash_profile
    ~/.dmrc: home/.dmrc
    ~/.mailcap: home/.mailcap
    ~/.xinitrc: home/.xinitrc
    #~/.nvidia-xinitrc: home/.nvidia-xinitrc
    ~/.xprofile: home/.xprofile
    ~/.xsession: home/.xsession
    ~/.zshenv: home/.zshenv
    ~/.terminfo: home/.terminfo

    # bin
    ~/.local/bin: bin

    # share

    ## themes
    ~/.local/share/themes: share/themes
    ~/.themes: share/themes
    # theme + wal
    ~/.config/wal/templates/gtkrc.css.base: ~/.local/share/themes/FlatColor/gtk-2.0/gtkrc.base
    ~/.config/wal/templates/gtk3.css.base: ~/.local/share/themes/FlatColor/gtk-3.0/gtk.css.base
    ~/.config/wal/templates/gtk32.css.base: ~/.local/share/themes/FlatColor/gtk-3.20/gtk.css.base

    ## icons
    ~/.local/share/icons: share/icons
    #- ~/.icons: share/icons

    ## fonts
    ~/.local/share/fonts: share/fonts

    ## applications
    ~/.local/share/applications/:
      glob: true
      path: share/applications/*

    ## common configs
    ~/.config/:
      glob: true
      path: config_simple/*

    # special configs
    ## mutt
    ~/.config/mutt/muttrc: config/mutt/muttrc
    ## vim
    #~/.config/vim/vimrc: config/nvim/init.vim
    ~/.config/vim/init.vim: config/nvim/init.vim
    ~/.config/vim/abbreviations.vim: config/nvim/abbreviations.vim
    ~/.config/vim/automation.vim: config/nvim/automation.vim
    ~/.config/vim/plugins.vim: config/nvim/plugins.vim
    ~/.config/vim/scripts.vim: config/nvim/scripts.vim
    ~/.config/vim/variables.vim: config/nvim/variables.vim
    ~/.config/vim/autoload: config/nvim/autoload
    ~/.config/vim/colors: config/nvim/colors
    ~/.config/vim/ftplugin: config/nvim/ftplugin
    ~/.config/vim/spell: config/nvim/spell
    ~/.config/qutebrowser/:
      glob: true
      path: config/qutebrowser/*
      create: true

    ## shell
    ~/.config/shell/:
      glob: true
      path: config/shell/*
    ~/.config/shell/.zprofile: config/shell/.zprofile
    ~/.config/shell/.zshrc: config/shell/.zshrc

    ## transmission
    ~/.config/transmission-daemon/settings.json: "config/transmission-daemon/settings.json"

    ## inkscape
    ~/.config/inkscape/preferences.xml:
      create: true
      path: config/inkscape/preferences.xml
    ## gimp
    ~/.config/GIMP/2.10/:
      glob: true
      path: config/GIMP/2.10/*

    ## wal
    ~/.config/wal/templates/:
      glob: true
      path: config/wal/templates/*
    # wal templates
    ~/.config/wal/templates/dunstrc.base: ~/.config/dunst/dunstrc.base
    ~/.config/wal/templates/config.ini.base: ~/.config/keepmenu/config.ini.base
    ~/.config/wal/templates/mpv.conf.base: ~/.config/mpv/mpv.conf.base
    ~/.config/wal/templates/zathura_light.base: ~/.config/zathura/zathura_light.base
    ~/.config/wal/templates/zathura_dark.base: ~/.config/zathura/zathura_dark.base

    # safe stuff
    ~/.config/mutt/aliases: ~/cld/Dropbox/home/config/mutt/aliases
    ~/.config/oauth2token/isync: ~/cld/Dropbox/home/config/oauth2token/isync
    ~/.config/qutebrowser/bookmarks: ~/cld/Dropbox/home/config/qutebrowser/bookmarks
    ~/.config/qutebrowser/quickmarks: ~/cld/Dropbox/home/config/qutebrowser/quickmarks

- shell:
  - ["fc-cache -vf ~/.local/share/fonts", Installing fonts]
  - ["xrdb -merge ~/.config/Xresources/main", Updating X resources]
  - ["cd ~/.local/bin/dmenu; make; sudo make install", Making dmenu]
  - ["cd ~/.local/bin/st; make; sudo make install", Making st]
