#!/bin/sh

INSTALL_TABLET=true

ARCH=
AUR=

# wget, curl, git
ARCH="$ARCH wget curl git"

# ripgrep
ARCH="$ARCH ripgrep"

# compression
ARCH="$ARCH zip unzip unrar"

# ssh client
ARCH="$ARCH openssh"

# zsh
ARCH="$ARCH zsh zsh-syntax-highlighting"

# X
ARCH="$ARCH xorg xorg-server xorg-xinit xorg-apps"

# clipboard
ARCH="$ARCH xclip xsel xdotool"

# notification
ARCH="$ARCH libnotify dunst"

# wallpaper setting
ARCH="$ARCH xwallpaper"

# alsa and pulse
ARCH="$ARCH alsa alsa-utils alsa-tools pulseaudio-alsa pavucontrol"
AUR="$AUR pulseaudio pamixer"

# mounting drives
ARCH="$ARCH udevil"

# file manager
ARCH="$ARCH thunar"
AUR="$AUR lf"
ARCH="$ARCH fzy"

# browsers
ARCH="$ARCH qutebrowser firefox"

# torrent
ARCH="$ARCH transmission-cli"
# torrent visualizer
AUR="$AUR yay tremc"

# mail
ARCH="$ARCH neomutt urlscan"

# window manager
ARCH="$ARCH bspwm yad"
AUR="$AUR polybar networkmanager-dmenu"
ARCH="$ARCH compton sox unclutter redshift scrot acpi brightnessctl mpv"

# e-reader
ARCH="$ARCH zathura zathura-cb zathura-djvu zathura-pdf-mupdf zathura-ps"

# screenshot
ARCH="$ARCH scrot"

# making mouse cursor disappear
ARCH="$ARCH unclutter"

# mpd
ARCH="$ARCH mpd mpc ncmpcpp"

# theming
AUR="$AUR pywal"

# youtube-dl
ARCH="$ARCH youtube-dl"

# wacom tablet
$INSTALL_TABLET &&
  ARCH="$ARCH xf86-input-wacom kcm-wacomtablet"

# clounds
AUR="$AUR dropbox dropbox-cli"

# security
AUR="$AUR keepassx2 keepmenu"

# lightdm
ARCH="$ARCH lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings"
# xinit-xsession for using xinit from lightdm
AUR="$AUR xinit-xsession"


# actually installing stuff

# aur managar
if ! `which yay 1>/dev/null 2>&1`
then
  sudo pacman -Syu --needed --noconfirm git
  HERE="$PWD"
  cd /tmp
  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepkg -si
  cd "$HERE"
fi

sudo pacman -Syu --needed --noconfirm $ARCH
yay -S --sudoloop --needed --noconfirm $AUR


# enabling pulse in current session
pulseaudio --start
